<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Salon.Application/Salon.Application.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>
</Project>
